force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <description>Contains all the surveys</description>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Question__c/Survey_Question__c.object-meta.xml
<CustomObject>
    <description>Contains all questions related to surveys</description>
    <label>Survey Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Survey Question number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Question__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is the question active?</description>
    <inlineHelpText>check this box if the question is active</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Survey_Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <description>Question</description>
    <inlineHelpText>Your Question</inlineHelpText>
    <label>Question</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Survey_Question__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Radio</fullName>
            </value>
            <value>
                <fullName>Checkbox</fullName>
            </value>
            <value>
                <fullName>Descriptive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Survey_Question_Response__c/Survey_Question_Response__c.object-meta.xml
<CustomObject>
    <label>Survey Question Response</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Survey Question Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Question_Response__c/fields/Survey_Question__c.field-meta.xml
<CustomField>
    <fullName>Survey_Question__c</fullName>
    <label>Survey Question</label>
    <referenceTo>Survey_Question__c</referenceTo>
    <relationshipLabel>Survey Question Responses</relationshipLabel>
    <relationshipName>Survey_Question_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/QuestionController.cls
public with sharing class QuestionController {
 	@AuraEnabled
    public static Survey_Question__c saveQuestion(String qtype,String question,boolean active,boolean required,
                                                  String choices,Id recordId) {
        // Perform isUpdateable() checking first, then
        //Building__c mybuilding = [Select Id FROM Building__c where Id=: recid ];
       // Flat__c myflat = new Flat__c(Name='1',Floor__c='2',Building__c = 'a022v00001MS8LXAA1');
           
        
        Survey_Question__c qs = new Survey_Question__c(Type__c=qtype,Question__c=question,Active__c=active,
                                                       Required__c=required,Choices__c=choices,Survey__c=recordId);
        
       
        try
        {
          insert qs;  
        }
       catch(Exception ex)
       {
          System.debug('>>>>>>>>>>>>>'+ex.getMessage());
        }
       return qs;
        
    }
    
    @AuraEnabled
    public static Survey_Question__c updateQuestion(Id id,String qtype,String question,boolean active,boolean required,
                                                  String choices,Id recordId) {
        // Perform isUpdateable() checking first, then
        //Building__c mybuilding = [Select Id FROM Building__c where Id=: recid ];
       // Flat__c myflat = new Flat__c(Name='1',Floor__c='2',Building__c = 'a022v00001MS8LXAA1');
           
        
        Survey_Question__c qs = new Survey_Question__c(Id = id,Type__c=qtype,Question__c=question,Active__c=active,
                                                       Required__c=required,Choices__c=choices,Survey__c=recordId);
        
       
        try
        {
          update qs;  
        }
       catch(Exception ex)
       {
          System.debug('>>>>>>>>>>>>>'+ex.getMessage());
        }
       return qs;
        
    }
    
    @AuraEnabled
    public static List<Survey_Question__c> getQuestions(Id recordId){
        
        return [SELECT Id, Active__c,Choices__c,Required__c, Question__c,Type__c FROM Survey_Question__c WHERE Survey__r.Id = :recordId ORDER BY CreatedDate ASC];
    
    }
    
    @AuraEnabled
    public static List<Survey_Question__c> getSurveyQuestions(Id recordId){
        
        return [SELECT Id, Active__c,Choices__c,Required__c, Question__c,Type__c FROM Survey_Question__c
                WHERE (Survey__r.Id = :recordId AND Active__c=True)];
    
    }
    
    @AuraEnabled
    public static void deleteQuestion(Id recordId) {
        Survey_Question__c qs = [SELECT Id,Name FROM Survey_Question__c WHERE Id = :recordId];
        delete qs;
    }
    
    @AuraEnabled
    public static void submitSurvey(Map<String,String> surveyMap,Id recordId){
		System.debug(surveyMap);
      
        List<Survey_Question_Response__c> answerList = new List<Survey_Question_Response__c>();
        for(String id:surveyMap.keySet()){
            
             System.debug(surveyMap.get(id));
            
        	Survey_Question_Response__c ans = new Survey_Question_Response__c(Response__c=surveyMap.get(id),
                                                                              Survey_Question__c=id);
            answerList.add(ans);
        }
    
        System.debug(answerList);
        try{
            insert answerList;
        }catch(Exception ex){
          System.debug('>>>>>>>>>>>>>'+ex.getMessage());
        }
    }
    
    
    
}